# -*- coding: utf-8 -*-
"""「EDA&RegressionModel.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHTTs58gBWXpl4Rk720p3t8eFTtwS1-g
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

bike_data = pd.read_csv('train.csv')
print('資料集:',bike_data.shape)
bike_data.head()

bike_data.info()

bike_data.describe()

bike_data['date'] = bike_data['datetime'].apply(lambda x: x.split()[0])
bike_data['year'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[0]).astype('int64')
bike_data['month'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[1]).astype('int64')
bike_data['day'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[2]).astype('int64')
bike_data['hour'] = bike_data['datetime'].apply(lambda x: x.split()[1].split(':')[0]).astype('int64')
bike_data['weekday'] = bike_data['datetime'].apply(lambda x: pd.to_datetime(x).weekday())
bike_data.head()

seasonDf=pd.DataFrame()
seasonDf=pd.get_dummies(bike_data.season,prefix='season')
seasonDf.head()

bike_data=pd.concat([bike_data,seasonDf],axis=1)

weatherDf=pd.DataFrame()
weatherDf=pd.get_dummies(bike_data.weather,prefix='weather')
weatherDf.head()

bike_data=pd.concat([bike_data,weatherDf],axis=1)

fig = plt.subplots(figsize=(20,20))
ax1 = plt.subplot(3,3,1)
df_number = bike_data[['casual','registered']].sum()
plt.pie(df_number,labels=['casual','registered'],shadow=True,autopct='%1.1f%%')
plt.title("User structure diagram")

df_count2 = bike_data.groupby(['year','month'],as_index=False).agg({'date':'min','count':'mean'})
fig = plt.figure(figsize=(30,10))
ax = plt.subplot(1,1,1)
plt.plot(df_count2['date'],df_count2['count'],marker='o',linewidth=1.3,label='Monthly average')
ax.set_title('Change trend of average count per month in two years',fontsize=20)
ax.set_xlabel('date',fontsize=20,weight='light')
ax.set_ylabel('Count',fontsize=20,weight='light')

x = []
for i in range(24):
    x.append(str(i))
y = []
for i in range(24):
    y.append(bike_data[bike_data["hour"]==i]["count"].sum())
plt.figure(figsize=(25,10))
for i in range(len(x)):
    height = y[i]
    plt.text(x[i], height + 1.9, '%.1f' %height, ha='center', va='bottom', size = 12)
plt.title("Usage by time zone")
plt.xlabel("hour",fontsize=20)
plt.ylabel("usage",fontsize=20)
plt.plot(x,y,color = '#005766')

#查看用戶數在不同季節的變化
fig = plt.subplots(figsize=(20,20))
ax1 = plt.subplot(4,2,1)
df_season = bike_data.groupby([bike_data['season']]).agg({'casual':'mean','registered':'mean'})
df_season.plot.bar(title='Change graph of users in different seasons',stacked=True,ax=ax1)
ax1.set_xticklabels(['Spring','Summer','Fall','Winter'],rotation='horizontal')
plt.xlabel('Season')
plt.ylabel('Number of Users')
plt.show()
#查看用戶數在不同月份的變化
fig = plt.figure(figsize=(10,5))
ax2 = ax1 = fig.add_subplot(1,1,1)
df=bike_data.groupby([bike_data['month']]).agg({'casual':'mean','registered':'mean'})
df.plot(ax=ax2,)
plt.title('Change graph of users in different months')
plt.xlabel('time(month)')
plt.ylabel('Number of User')
plt.show()

x = ["spring","summer","fall","winter"]
y , y1, y2 = [],[],[]
for i in range(1,5):
    y.append(np.mean(bike_data[bike_data["season"]==i]["temp"].values.tolist()))
    y1.append(np.mean(bike_data[bike_data["season"]==i]["atemp"].values.tolist()))
    y2.append(np.mean(bike_data[bike_data["season"]==i]["count"].values.tolist()))

plt.figure(figsize=(15,5))

for i in range(len(x)): # season counts visualize
    height = y2[i]
    plt.text(x[i], height + 0.25, '%.1f' %height, ha='center', va='bottom', size = 12)
plt.title("Season's average temp/atemp")
plt.xlabel("Season")
plt.ylabel("Counts")
plt.bar(x,y2,color="skyblue",label="count")

ay1 = plt.twinx()
for i in range(len(x)): # average temp numb visualize
    height = y[i]
    plt.text(x[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)

for i in range(len(x)):# average atemp numb visualize
    height = y1[i]
    plt.text(x[i], height  -0.9, '%.1f' %height, ha='center', va='bottom', size = 12)
ay1.plot(x,y1,color="red",label="average atemp")
ay1.plot(x,y,color='yellow',label="average temp")
plt.ylabel("temp")
plt.legend()

#查看用戶數在工作日的分布情況
fig = plt.subplots(figsize=(20,20))
ax6 = plt.subplot(4,2,1)
df_workingday = bike_data.groupby([bike_data['workingday']]).agg({'casual':'mean','registered':'mean'})
df_workingday.plot(title='Situation map of users on weekdays',ax=ax6)
plt.axis([0,1,0,200])
plt.xlabel('working day')
plt.ylabel('total number of users')
plt.show()
#查看用戶數在假期的分布情況
fig = plt.figure(figsize=(20,20))
ax7 = plt.subplot(4,2,1)
df_holiday = df = bike_data.groupby([bike_data['holiday']]).agg({'casual':'mean','registered':'mean'})
df_workingday.plot.bar(title='Situation map of users on holidays',ax=ax7,stacked=True)
plt.xlabel('holiday')
plt.ylabel('total number of users')
plt.show()

bike_data_workingday=bike_data[bike_data['workingday']==1]
bike_data_workingday.head()

fig = plt.figure(figsize=(10,5))
ax13 = fig.add_subplot(2,1,1)
df_workingday = bike_data_workingday.groupby([bike_data_workingday['hour']]).agg({'casual':'mean', 'registered':'mean'})

df_workingday.plot(ax=ax13,kind='area',alpha=0.6)
plt.title('Time distribution map of the number of users on workingdays')
#查看用戶在假期的時刻分布情況
#Holiday:假期(1:是, 0:不是)
bike_data_holiday = bike_data[bike_data['holiday']==1]
fig = plt.figure(figsize=(10,5))
ax14 = ax13 = fig.add_subplot(2,1,2)
df_holiday = bike_data_holiday.groupby([bike_data_holiday['hour']]).agg({'casual':'mean', 'registered':'mean'})
df_holiday.plot(ax=ax14,kind='area',alpha=0.6)
plt.title('Time distribution map of the number of users on holidays')

fig = plt.subplots(figsize=(20,20))
ax1 = plt.subplot(4,2,1)
df_season = bike_data.groupby([bike_data['weather']]).agg({'casual':'mean', 'registered':'mean'})
df_season.plot.bar(title='Change graph of the total number of users in different weather conditions',stacked=True,ax=ax1)
ax1.set_xticklabels(['sunny with little cloud','cloudy mist','light rain or snow','heavy rain or snow'],rotation='horizontal')
plt.xlabel('weather')
plt.ylabel('total of users')
plt.show()

#查看溫度與用戶數的圖形關係
fig = plt.subplots(figsize=(20,10))
ax1 = plt.subplot(2,2,1)
df = bike_data.groupby([bike_data['temp']]).agg({'casual':'mean', 'registered':'mean'})
df.plot(ax=ax1,title='Change graph of the total number of users at different temparature')
plt.xlabel('temparature')
plt.ylabel('total of users')
#查看體感溫度與用戶數的圖形關係
fig = plt.figure(figsize=(20,10))
ax10 = ax1 = fig.add_subplot(2,2,2)
df_atemp = bike_data.groupby([bike_data['atemp']]).agg({'casual':'mean', 'registered':'mean'})
df_atemp.plot(ax=ax10,alpha=0.8,title='Change graph of the total number of users at different atemp')
plt.xlabel('atemp')
plt.ylabel('total of users')

#查看濕度與用戶數的圖形關係
fig = plt.figure(figsize=(20,10))
ax3 = ax1 = fig.add_subplot(2,2,3)
df_atemp = bike_data.groupby([bike_data['humidity']]).agg({'casual':'mean', 'registered':'mean'})
df_atemp.plot(ax=ax3,title='Change graph of the total number of users at different humidity')
plt.xlabel('humidity')
plt.ylabel('total of users')
#查看風速與用戶數的圖形關係
fig = plt.figure(figsize=(20,10))
ax4 = ax1 = fig.add_subplot(2,2,4)
df_atemp = bike_data.groupby([bike_data['windspeed']]).agg({'casual':'mean', 'registered':'mean'})
df_atemp.plot(ax=ax4,title='Change graph of the total number of users at different windspeed')
plt.xlabel('windspeed')
plt.ylabel('total of users')

fig = plt.figure(figsize=(10,5))
ax2 = fig.add_subplot(1,1,1)
df_temp = bike_data[['temp','count']]
df_temp.plot(x='temp', y='count',kind='scatter',ax=ax2)
plt.xlabel('temp')
plt.ylabel('total of users')
plt.title('Change graph of the total number of users at different temparature')
plt.axis([0,45,0,1000])

fig = plt.figure(figsize=(10,5))
ax3 = fig.add_subplot(1,1,1)
df_temp = bike_data[['atemp','count']]
df_temp.plot(x='atemp', y='count',kind='scatter',ax=ax3)
plt.xlabel('atemp')
plt.ylabel('total of users')
plt.title('Change graph of the total number of users at different atemp')
plt.axis([0,45,0,1000])

fig = plt.figure(figsize=(10,5))
ax2 = fig.add_subplot(1,1,1)
df_temp = bike_data[['humidity','count']]
df_temp.plot(x='humidity', y='count',kind='scatter',ax=ax2)
plt.xlabel('humidity')
plt.ylabel('total of users')
plt.title('Change graph of the total number of users at different humidity')
plt.axis([0,45,0,1000])

fig = plt.figure(figsize=(10,5))
ax3 = fig.add_subplot(1,1,1)
df_temp = bike_data[['windspeed','count']]
df_temp.plot(x='windspeed', y='count',kind='scatter',ax=ax3)
plt.xlabel('windspeed')
plt.ylabel('total of users')
plt.title('Change graph of the total number of users at different windspeed')
plt.axis([0,45,0,1000])

fig = plt.figure(figsize=(10,5))
ax2 = fig.add_subplot(1,1,1)
df_temp = bike_data[['hour','count']]
df_temp.plot(x='hour', y='count',kind='scatter',ax=ax2)
plt.xlabel('hour')
plt.ylabel('total of users')
plt.title('Change graph of the total number of users at different hour')
plt.axis([0,24,0,1000])

import seaborn as sns
bike_data = pd.read_csv('train.csv')
bike_data['year'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[0]).astype('int64')
bike_data['month'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[1]).astype('int64')
bike_data['day'] = bike_data['datetime'].apply(lambda x: x.split()[0].split('-')[2]).astype('int64')
bike_data['hour'] = bike_data['datetime'].apply(lambda x: x.split()[1].split(':')[0]).astype('int64')

fig = plt.figure(figsize=(15,10))
ax2 = fig.add_subplot(1,1,1)
df = pd.concat([bike_data.iloc[:, 1:]],axis=1)
corrdf = df.corr()
mask = np.array(corrdf)
mask[np.tril_indices_from(mask)] = False
sns.heatmap(corrdf, mask=mask, annot=True, square=True, ax=ax2)

bike_data.corr()

#bike_data.head(20)
#print(bike_data[bike_data['windspeed']>50])
#print(bike_data[bike_data['weather']==4])
print(bike_data[bike_data['day']>=19])

#prepare test set
test = pd.read_csv('test.csv')
test['year'] = test['datetime'].apply(lambda x: x.split()[0].split('-')[0]).astype('int64')
test['month'] = test['datetime'].apply(lambda x: x.split()[0].split('-')[1]).astype('int64')
test['day'] = test['datetime'].apply(lambda x: x.split()[0].split('-')[2]).astype('int64')
test['hour'] = test['datetime'].apply(lambda x: x.split()[1].split(':')[0]).astype('int64')

#select features that are positive correlated to counts by heatmap
features = ['season','weather','humidity','temp','atemp','year','month','hour','windspeed']

x_train = bike_data[features]
x_test = test[features]
y_train = bike_data["count"]

#regression model
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()
model = RandomForestRegressor(n_estimators=300, n_jobs = -1 , random_state = 15)
model.fit(x_train,y_train)
relation_square = model.score(x_train, y_train)
print('relation_square: ', relation_square)
plt.figure(figsize=(20,5))
y_p = model.predict(x_train)
ax1 = sns.kdeplot(y_train,label = 'y_train',color="red")
ax2 = sns.kdeplot(y_p,label = 'y_pred',color="blue")
plt.legend()
plt.show()

predictions = model.predict(x_test)
predictions